### ISSUE TITLE
General behaviour/batteries not staying synced

### ISSUE THREAD

**Issue by lily-bit-0** [estokes/pinephone-kbpwrd#1]
First of all, thank you for making and publishing this! So far I’ve run kbpwrd for two full charges and two (almost) full discharges. I’m putting my observations here just in case you find them useful. I’m also still new to all of this and I’ve never opened an issue on anyone’s repo before, so I hope I’m doing this right. My setup: PinePhone 1.2 Convergence, Manjaro testing branch, Plasma Mobile 5.24.4, Kernel 5.17.1-2-MANJARO-ARM, 5V 3A PD power supply, keyboard case ordered as soon as it was available

Small note before I get to the main stuff: The readme says it keeps the PP above 20% while the code comment says 30. I’ve skimmed through the code which was certainly illuminating, but I don’t know anything about Rust, so I’m not sure which of the two it actually does. It looks like 30.

During the first charge when both batteries were low, plugging in a power supply made it set the KB limit to 1.9A and the PP limit to 0.5A. Doing something very power intensive decreased the KB limit to 1.4A and increased the PP limit to only 0.9 which still resulted in a net -0.6A, eventually resulting in the PP reaching 0% despite being connected to a power supply.

Keeping both batteries at a similar capacity didn’t work most of the time. During the first charge, the KB reached 99% when the PP had only reached 50%. The second time it was 99% 75%. When the KB is already full but the PP is not, it doesn’t immediately set the PP limit to its maximum.

During the first discharge the capacities were reasonably in sync, except for when I tested doing something power intensive for a short time, in which case the PP capacity went up and the KB down. The second time discharging always kept the PP around 100% and completely discharged the KB first. When I manually set the PP limit to 0.5A while discharging and using it normally but constantly throughout this Sunday (mostly emacs (also to write this) and other terminal stuff as well as cmus, and some apparently not hardware accelerated mpv during meals), both batteries were staying quite synced, as you suggested in the readme regarding 0.5A being the right limit most of the time.

During discharges, kbpwrd always engages in an endless cycle of setting the PP limit to something high, lowering it incrementally, as a last step setting the KB offline, and then setting it online again and repeating the process. This makes it seem like its not really balancing the limits based on what the phone currently needs and just blindly cycling through the limits. As a consequence of constantly setting the KB offline and online, Plasma Mobile plays the plugged out and plugged in sounds every ten seconds or so, though I guess this should be considered one of PlaMo’s issues when facing (this instance of) multiple batteries.

When suspending while KB -> PP charging is on instead of the KB being set to off, the KB will continue to charge the PP with the last set limit while the PP uses very little power, making both batteries go very much out of sync.

**Comment by estokes** [comment]
Thanks for your feedback. Megi is integrating this functionality into the kernel, as such this project is deprecated, please use the kernel driver going forward.
