### ISSUE TITLE
KB current when offline at -0.1A instead of usual -0.01 – -0.005

### ISSUE THREAD

**Issue by lily-bit-0** [estokes/pinephone-kbpwrd#2]
When kbpwrd sets the KB offline during discharges, the KB always still reports a current value of -0.1A, unlike the -0.011A when set offline using Megi’s driver or when I manually set `/sys/class/power_supply/ip5xxx-boost/online` to 0. The same -0.1A is displayed when not charging while a power supply is plugged in (because it’s (supposedly) full), while it would only be at -0.0055A in this state without kbpwrd. I don’t know if this matters but this suggests it somehow wastes charge.

**Comment by estokes** [comment]
Thanks for your feedback. Megi is integrating this functionality into the kernel, as such this project is deprecated, please use the kernel driver going forward.
